7.2.0

diff --git a/.github/workflows/test-windows.yml b/.github/workflows/test-windows.yml
--- a/.github/workflows/test-windows.yml
+++ b/.github/workflows/test-windows.yml
@@ -1,181 +1,119 @@
 name: Test Windows
 
-on:
-  push:
-    paths-ignore:
-      - ".github/workflows/docs.yml"
-      - "docs/**"
-  pull_request:
-    paths-ignore:
-      - ".github/workflows/docs.yml"
-      - "docs/**"
-  workflow_dispatch:
-
-permissions:
-  contents: read
-
-concurrency:
-  group: ${{ github.workflow }}-${{ github.ref }}
-  cancel-in-progress: true
+on: [push, pull_request]
 
 jobs:
   build:
-    runs-on: windows-latest
+    runs-on: windows-2019
     strategy:
       fail-fast: false
       matrix:
-        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12-dev"]
+        python-version: ["3.5", "3.6", "3.7", "3.8", "pypy3"]
         architecture: ["x86", "x64"]
         include:
-          # PyPy 7.3.4+ only ships 64-bit binaries for Windows
-          - python-version: "pypy3.8"
+          - architecture: "x86"
+            platform-vcvars: "x86"
+            platform-msbuild: "Win32"
+          - architecture: "x64"
+            platform-vcvars: "x86_amd64"
+            platform-msbuild: "x64"
+        exclude:
+          # PyPy does not support 64-bit on Windows
+          - python-version: "pypy3"
             architecture: "x64"
-          - python-version: "pypy3.9"
-            architecture: "x64"
-
     timeout-minutes: 30
 
     name: Python ${{ matrix.python-version }} ${{ matrix.architecture }}
 
     steps:
     - name: Checkout Pillow
-      uses: actions/checkout@v3
+      uses: actions/checkout@v2
 
     - name: Checkout cached dependencies
-      uses: actions/checkout@v3
+      uses: actions/checkout@v2
       with:
         repository: python-pillow/pillow-depends
         path: winbuild\depends
 
-    - name: Checkout extra test images
-      uses: actions/checkout@v3
+    - name: Cache pip
+      uses: actions/cache@v1
       with:
-        repository: python-pillow/test-images
-        path: Tests\test-images
+        path: ~\AppData\Local\pip\Cache
+        key:
+          ${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.architecture }}-${{ hashFiles('**/.github/workflows/test-windows.yml') }}
+        restore-keys: |
+          ${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.architecture }}-
+          ${{ runner.os }}-${{ matrix.python-version }}-
 
     # sets env: pythonLocation
     - name: Set up Python
-      uses: actions/setup-python@v4
+      uses: actions/setup-python@v1
       with:
         python-version: ${{ matrix.python-version }}
         architecture: ${{ matrix.architecture }}
-        cache: pip
-        cache-dependency-path: ".github/workflows/test-windows.yml"
 
-    - name: Print build system information
-      run: python3 .github/workflows/system-info.py
-
-    - name: python3 -m pip install setuptools wheel pytest pytest-cov pytest-timeout defusedxml
-      run: python3 -m pip install setuptools wheel pytest pytest-cov pytest-timeout defusedxml
-
-    - name: Install dependencies
-      id: install
-      run: |
-        7z x winbuild\depends\nasm-2.16.01-win64.zip "-o$env:RUNNER_WORKSPACE\"
-        echo "$env:RUNNER_WORKSPACE\nasm-2.16.01" >> $env:GITHUB_PATH
-
-        choco install ghostscript --version=10.0.0.20230317
-        echo "C:\Program Files\gs\gs10.00.0\bin" >> $env:GITHUB_PATH
-
-        # Install extra test images
-        xcopy /S /Y Tests\test-images\* Tests\images
-
-        # make cache key depend on VS version
-        & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" `
-          | find """catalog_buildVersion""" `
-          | ForEach-Object { $a = $_.split(" ")[1]; echo "vs=$a" >> $env:GITHUB_OUTPUT }
+    - name: Set up TCL
+      if: "contains(matrix.python-version, 'pypy')"
+      run: Write-Host "::set-env name=TCL_LIBRARY::$env:pythonLocation\tcl\tcl8.5"
       shell: pwsh
 
-    - name: Cache build
-      id: build-cache
-      uses: actions/cache@v3
-      with:
-        path: winbuild\build
-        key:
-          ${{ hashFiles('winbuild\build_prepare.py') }}-${{ hashFiles('.github\workflows\test-windows.yml') }}-${{ env.pythonLocation }}-${{ steps.install.outputs.vs }}
+    - name: Print build system information
+      run: python .github/workflows/system-info.py
 
-    - name: Prepare build
-      if: steps.build-cache.outputs.cache-hit != 'true'
+    - name: pip install wheel pytest pytest-cov
+      run: python -m pip install wheel pytest pytest-cov
+
+    - name: Prepare dependencies
       run: |
-        & python.exe winbuild\build_prepare.py -v --python $env:pythonLocation
+        7z x winbuild\depends\nasm-2.14.02-win64.zip "-o$env:RUNNER_WORKSPACE\"
+        Write-Host "::add-path::$env:RUNNER_WORKSPACE\nasm-2.14.02"
+
+        winbuild\depends\gs950w32.exe /S
+        Write-Host "::add-path::C:\Program Files (x86)\gs\gs9.50\bin"
+
+        xcopy /s winbuild\depends\test_images\* Tests\images\
+
+        & python.exe winbuild\build_prepare.py -v --python=$env:pythonLocation
       shell: pwsh
 
     - name: Build dependencies / libjpeg-turbo
-      if: steps.build-cache.outputs.cache-hit != 'true'
       run: "& winbuild\\build\\build_dep_libjpeg.cmd"
-
     - name: Build dependencies / zlib
-      if: steps.build-cache.outputs.cache-hit != 'true'
       run: "& winbuild\\build\\build_dep_zlib.cmd"
-
-    - name: Build dependencies / xz
-      if: steps.build-cache.outputs.cache-hit != 'true'
-      run: "& winbuild\\build\\build_dep_xz.cmd"
-
-    - name: Build dependencies / WebP
-      if: steps.build-cache.outputs.cache-hit != 'true'
-      run: "& winbuild\\build\\build_dep_libwebp.cmd"
-
     - name: Build dependencies / LibTiff
-      if: steps.build-cache.outputs.cache-hit != 'true'
       run: "& winbuild\\build\\build_dep_libtiff.cmd"
-
-    # for FreeType CBDT/SBIX font support
-    - name: Build dependencies / libpng
-      if: steps.build-cache.outputs.cache-hit != 'true'
-      run: "& winbuild\\build\\build_dep_libpng.cmd"
-
-    # for FreeType WOFF2 font support
-    - name: Build dependencies / brotli
-      if: steps.build-cache.outputs.cache-hit != 'true'
-      run: "& winbuild\\build\\build_dep_brotli.cmd"
-
+    - name: Build dependencies / WebP
+      run: "& winbuild\\build\\build_dep_libwebp.cmd"
     - name: Build dependencies / FreeType
-      if: steps.build-cache.outputs.cache-hit != 'true'
       run: "& winbuild\\build\\build_dep_freetype.cmd"
-
     - name: Build dependencies / LCMS2
-      if: steps.build-cache.outputs.cache-hit != 'true'
       run: "& winbuild\\build\\build_dep_lcms2.cmd"
-
     - name: Build dependencies / OpenJPEG
-      if: steps.build-cache.outputs.cache-hit != 'true'
       run: "& winbuild\\build\\build_dep_openjpeg.cmd"
 
-    # GPL licensed
+    # GPL licensed; skip if building wheels
     - name: Build dependencies / libimagequant
-      if: steps.build-cache.outputs.cache-hit != 'true'
+      if: "github.event_name != 'push'"
       run: "& winbuild\\build\\build_dep_libimagequant.cmd"
 
     # Raqm dependencies
     - name: Build dependencies / HarfBuzz
-      if: steps.build-cache.outputs.cache-hit != 'true'
       run: "& winbuild\\build\\build_dep_harfbuzz.cmd"
-
-    # Raqm dependencies
     - name: Build dependencies / FriBidi
-      if: steps.build-cache.outputs.cache-hit != 'true'
       run: "& winbuild\\build\\build_dep_fribidi.cmd"
-
-    # trim ~150MB for each job
-    - name: Optimize build cache
-      if: steps.build-cache.outputs.cache-hit != 'true'
-      run: rmdir /S /Q winbuild\build\src
-      shell: cmd
+    - name: Build dependencies / Raqm
+      run: "& winbuild\\build\\build_dep_libraqm.cmd"
 
     - name: Build Pillow
       run: |
-        $FLAGS=""
-        if ('${{ github.event_name }}' -ne 'pull_request') { $FLAGS="--disable-imagequant" }
-        & winbuild\build\build_pillow.cmd $FLAGS install
+        & winbuild\build\build_pillow.cmd install
         & $env:pythonLocation\python.exe selftest.py --installed
       shell: pwsh
 
-    # skip PyPy for speed
+    # failing with PyPy3
     - name: Enable heap verification
       if: "!contains(matrix.python-version, 'pypy')"
-      run: |
-        & reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\python.exe" /v "GlobalFlag" /t REG_SZ /d "0x02000000" /f
+      run: "& 'C:\\Program Files (x86)\\Windows Kits\\10\\Debuggers\\x86\\gflags.exe' /p /enable $env:pythonLocation\\python.exe"
 
     - name: Test Pillow
       run: |
@@ -187,10 +125,10 @@ jobs:
       if: failure()
       run: |
         mkdir -p Tests/errors
-      shell: bash
+      shell: pwsh
 
     - name: Upload errors
-      uses: actions/upload-artifact@v3
+      uses: actions/upload-artifact@v1
       if: failure()
       with:
         name: errors
@@ -202,7 +140,7 @@ jobs:
       shell: pwsh
 
     - name: Upload coverage
-      uses: codecov/codecov-action@v3
+      uses: codecov/codecov-action@v1
       with:
         file: ./coverage.xml
         flags: GHA_Windows
@@ -210,50 +148,87 @@ jobs:
 
     - name: Build wheel
       id: wheel
-      if: "github.event_name != 'pull_request'"
+      if: "github.event_name == 'push'"
       run: |
-        mkdir fribidi\${{ matrix.architecture }}
-        copy winbuild\build\bin\fribidi* fribidi\${{ matrix.architecture }}
-        setlocal EnableDelayedExpansion
-        for %%f in (winbuild\build\license\*) do (
-          set x=%%~nf
-          rem Skip FriBiDi license, it is not included in the wheel.
-          set fribidi=!x:~0,7!
-          if NOT !fribidi!==fribidi (
-            rem Skip imagequant license, it is not included in the wheel.
-            set libimagequant=!x:~0,13!
-            if NOT !libimagequant!==libimagequant (
-              echo. >> LICENSE
-              echo ===== %%~nf ===== >> LICENSE
-              echo. >> LICENSE
-              type %%f >> LICENSE
-            )
-          )
-        )
-        for /f "tokens=3 delims=/" %%a in ("${{ github.ref }}") do echo dist=dist-%%a >> %GITHUB_OUTPUT%
-        winbuild\\build\\build_pillow.cmd --disable-imagequant bdist_wheel
+        for /f "tokens=3 delims=/" %%a in ("${{ github.ref }}") do echo ::set-output name=dist::dist-%%a
+        winbuild\\build\\build_pillow.cmd bdist_wheel"
       shell: cmd
 
-    - name: Upload wheel
-      uses: actions/upload-artifact@v3
-      if: "github.event_name != 'pull_request'"
+    - uses: actions/upload-artifact@v2
+      if: "github.event_name == 'push'"
       with:
         name: ${{ steps.wheel.outputs.dist }}
         path: dist\*.whl
 
-    - name: Upload fribidi.dll
-      if: "github.event_name != 'pull_request' && matrix.python-version == 3.11"
-      uses: actions/upload-artifact@v3
-      with:
-        name: fribidi
-        path: fribidi\*
+  msys:
+    runs-on: windows-2019
 
-  success:
-    permissions:
-      contents: none
-    needs: build
-    runs-on: ubuntu-latest
-    name: Windows Test Successful
+    strategy:
+      fail-fast: false
+      matrix:
+        mingw: ["MINGW32", "MINGW64"]
+        include:
+          - mingw: "MINGW32"
+            package: "mingw-w64-i686"
+          - mingw: "MINGW64"
+            package: "mingw-w64-x86_64"
+
+    defaults:
+      run:
+        shell: bash.exe --login -eo pipefail "{0}"
+    env:
+      MSYSTEM: ${{ matrix.mingw }}
+      CHERE_INVOKING: 1
+
+    timeout-minutes: 30
+    name: MSYS2 ${{ matrix.mingw }}
+
     steps:
-      - name: Success
-        run: echo Windows Test Successful
+      - uses: actions/checkout@v2
+
+      - name: Set up shell
+        run: echo ::add-path::C:\msys64\usr\bin\
+        shell: pwsh
+
+      - name: Install Dependencies
+        run: |
+          pacman -S --noconfirm \
+              ${{ matrix.package }}-python3-pip \
+              ${{ matrix.package }}-python3-setuptools \
+              ${{ matrix.package }}-python3-pytest \
+              ${{ matrix.package }}-python3-pytest-cov \
+              ${{ matrix.package }}-python3-cffi \
+              ${{ matrix.package }}-python3-olefile \
+              ${{ matrix.package }}-python3-numpy \
+              ${{ matrix.package }}-python3-pyqt5 \
+              ${{ matrix.package }}-python3-numpy \
+              ${{ matrix.package }}-freetype \
+              ${{ matrix.package }}-lcms2 \
+              ${{ matrix.package }}-libwebp \
+              ${{ matrix.package }}-libjpeg-turbo \
+              ${{ matrix.package }}-openjpeg2 \
+              ${{ matrix.package }}-libimagequant \
+              ${{ matrix.package }}-libraqm \
+              ${{ matrix.package }}-ghostscript \
+              subversion
+
+          python3 -m pip install pyroma
+
+          pushd depends && ./install_extra_test_images.sh && popd
+
+      - name: Build Pillow
+        run: |
+          # libtiff is unable to open files
+          CFLAGS="-coverage" python3 setup.py build_ext --disable-tiff install
+
+      - name: Test Pillow
+        run: |
+          python3 selftest.py --installed
+          python3 -m pytest -vx --cov PIL --cov Tests --cov-report term --cov-report xml Tests
+
+      - name: Upload coverage
+        run: |
+          python3 -m pip install codecov
+          bash <(curl -s https://codecov.io/bash) -F GHA_Windows
+        env:
+          CODECOV_NAME: MSYS2 ${{ matrix.mingw }}
